### PR TITLE
Urls refactor

### PR DESCRIPTION
**Pull request by Evengard**
Refactored all URLs. Now every URL gets generated in request->makeUrl. Support of nonFURL added, support of manifest-based URL generation added, and hope that I broke nothing.

Well, really a HUGE pull request here. If ANY problems please don't hesitate to contact me - will try to fix ASAP.

If you have conflicts (mostly because of templates) - I also will help.

### CODE REVIEW

**Comment by Evengard** [comment]
Merged current 'develop' into this.

**Comment by rthrash** [comment]
I would also go ahead and merge the latest Dustin-dev-forums just in case some things have inadvertently left out of Dev. They shouldn't, but… 

Also FYI, the Mike Solr branch will be the next major effort that gets integrated. Not thinking that would affect your work in any significant work, but wanted to let you know. I think he's mostly done and ready to push for testing.

**Comment by Mark-H** [comment]
We've released 1.1 on Christmas Eve, and due to time constraints this feature was left out for now. 

Along with other bug fixes and improvements to the default theme, this will be the major new feature for 1.2.

**Comment by Mark-H** [comment]
So you know, I have not forgotten about this PR and am almost done implementing it in the new default theme. One huge ass pull request there ;)

**Comment by the-dunnock** [comment]
I have this under the gun right now and sorry that this did not make to 1.2-pl. Read the road map bit too late.

I have already merged this to current develop locally and resolved most of the conflicts with the default theme. So push to develop branch will be most likely to be due today. Also the plugin will be included within the push.

**Comment by the-dunnock** [comment]
@Evengard I have problem with the categories. All other forwarders work fine but trying to access /forums/category/3/ for example throws back to /forums/

[Edit] Got it working, it was an issues with the original controller loading method. Now /forum/category/1 for example works

**Pull request merged**
