### PR TITLE
Sql optimization

### PR DESCRIPTION
**Pull request by the-dunnock**
Fixes loads of SQL speed issues.

If using without installed, add next indexes manually with snippet or method you prefer:

$manager = $modx->getManager();
$manager->addIndex('disBoardClosure','PRIMARY');
$manager->addIndex('disCategory','rank');
$manager->addIndex('disSession','PRIMARY');
$manager->addIndex('disSession','place');

### CODE REVIEW

**Comment by Mark-H** [comment]
I think you meant getManager instead of getCacheManager ;)

```
$manager = $modx->getManager();
```

The PR really looks promising though. Am about to give it a quick spin on a tiny personal forum, though obviously the real test would be the MODX one..

**Comment by Mark-H** [comment]
It definitely feels a _lot_ snappier and I've not yet encountered any issues. :thumbsup:

**Comment by the-dunnock** [comment]
Heh, the cacheManager was accidental :). Pulled the command top of my head.

It should be quite lot snappier, runned small DOS tests from initial to last enhancement using http_load and static url list with all tests. The queries per second was 8.5 times more with the latest run and actually using 3 parallel connections versus 1 connection which I had for initial test.

Also the mark all read is lot faster than that. I have DB with 300k posts and 152k threads. And only running small VPS locally with 4 cores and 2Gb memory. Plus with percona server and not normal mysql.

There are still queries to be adjusted and actually need to check if I adjust one of the queries bundled with the fix also.

**Comment by the-dunnock** [comment]
Bad with commit message I am.

Latest commit also fixes default theme issues with search and improves search to function with all the fields included nicely.

**Pull request merged**
